# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
target 'FlutterNavite' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'SDWebImage', '~> 4.4.3'
  # Pods for FlutterNavite

  target 'FlutterNaviteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterNaviteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

flutter_application_path = '/Users/shengxin/Desktop/FlutterNavite/Flutter/flutter_module'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
